### ISSUE TITLE
Check if email is empty or allow for empty emails

### ISSUE THREAD

**Issue by melekes** [cosmos/fundraiser-cli#1]
![screen shot 2017-03-16 at 12 00 33](https://cloud.githubusercontent.com/assets/1282182/23987000/97efd272-0a40-11e7-8f34-32b5d7bd530a.png)

Otherwise, it is confusing. How could you send a copy of the wallet to an empty address?

**Comment by jaekwon** [comment]
closing because we don't use emails anymore.  thank you!
