### ISSUE TITLE
[SUGGESTION] Check password for basic entropy

### ISSUE THREAD

**Issue by melekes** [cosmos/fundraiser-cli#2]
https://blog.codinghorror.com/password-rules-are-bullshit/
"the simplest way to do this is to ensure that there are at least (x) unique characters out of (y) total characters."

This could be applied to both web and CLI versions.

Feel free to close this if it is not important.

**Comment by mappum** [comment]
This is very important, you're right that we should ensure passwords are strong. The entropy check will be good, and we should probably also check against a password list.

**Comment by jaekwon** [comment]
closing because we don't use passwords anymore.  thank you!
